# Python Basics

In [34]:
print("Hello, MAHAM NISAR!")

x = 10
y = 20
print("Sum:", x + y)


Hello, MAHAM NISAR!
Sum: 30


# Loops (all types)

# 1. for loop

In [14]:
for i in range(1, 6):
    print(i)

1
2
3
4
5


# 2. While loop

In [16]:
count = 1
while count <= 5:
    print(count)
    count += 1

1
2
3
4
5


# 3. Nested loop

In [17]:
for i in range(1, 4):
    for j in range(1, 3):
        print(i, j)

1 1
1 2
2 1
2 2
3 1
3 2


# 4. Break and Continue

In [18]:
for i in range(1, 6):
    if i == 3:
        continue
    if i == 5:
        break
    print(i)

1
2
4


# Functions (types)

# 1. function with parameters and return

In [32]:
def add(a, b):
    return a + b

print(add(5, 3))

8


# 2. lambda function

In [33]:
square = lambda x: x * x
print(square(4))

16


# Lists (8–14 methods)

In [25]:
my_list = [1, 2, 3, 4]

my_list.append(5)
my_list.extend([6, 7])
my_list.insert(1, 10)
my_list.remove(3)
my_list.pop()
my_list.sort()
my_list.reverse()
index = my_list.index(2)

print(my_list)
print("Index of 2:", index)


[10, 6, 5, 4, 2, 1]
Index of 2: 4


# Dictionaries:

# 1. List to Dictionary

In [29]:
keys = ['name', 'age', 'city']
values = ['MAHAM', 20, 'Lahore']
my_dict = dict(zip(keys, values))
print(my_dict)

{'name': 'MAHAM', 'age': 20, 'city': 'Lahore'}


# 2. Dictionary to List

In [30]:
dict_items = list(my_dict.items())
print(dict_items)

[('name', 'MAHAM'), ('age', 20), ('city', 'Lahore')]


# 3. Tuple

In [31]:
my_tuple = (1, 2, 3)
print(my_tuple)

(1, 2, 3)


# Heading 2: NumPy

In [35]:
import numpy as np


# 1. Arrays

In [27]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


# 2. Vectorized Operations

In [28]:
print(arr * 2)
print(arr + 5)

[2 4 6 8]
[6 7 8 9]


# Heading 3: Matrix Multiplication

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)
print(result)


[[19 22]
 [43 50]]


# Broadcasting

In [13]:
print(A + 10)

[[11 12]
 [13 14]]
